### ISSUE TITLE
Use MIT License?

### ISSUE THREAD

**Issue by splitbrain** [arokettu/monsterid#1]
Hi, original author here. Just for your interest, I just relicensed my code and graphics under the more permissive MIT license. It might be helpful to do the same with this repository? Thanks for maintaining this.

See https://github.com/splitbrain/monsterID

**Comment by arokettu** [comment]
Hi @splitbrain 
Done and released - [1.1.1](https://github.com/sandfoxme/monsterid/releases/tag/1.1.1)
Thanks for the library!
